# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana.host: "kibana:5601"
#metricbeat.autodiscover:
#  providers:
#    - type: docker
#      templates:
#        - condition:
#            contains:
#              docker.container.image: nginx
#          config:
#            - module: nginx
#              metricsets: [ "stubstatus" ]
#              hosts: "${data.docker.container.name}:${data.port}"
#              server_status_path: "nginx_status"

metricbeat.modules:
  - module: nginx
    enabled: true
    metricsets: [ "stubstatus" ]
    period: 5s
    hosts: [ "http://nginx" ]
    server_status_path: "nginx_status"
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enable: true

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.dashboards.enabled: true